import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import { buildDatabaseOptions } from './database.config.js';
import {
  AdmissionCriterionEntity,
  ApplicationAcademicDocumentEntity,
  ApplicationAcademicInformationEntity,
  ApplicationAddressEntity,
  ApplicationContactEntity,
  ApplicationDeclarationEntity,
  ApplicationEntity,
  ApplicationStatusAuditEntity,
  ApplicationProgrammeOptionEntity,
  ApplicationProgrammeSelectionEntity,
  CriteriaTypeEntity,
  DeclarationTypeEntity,
  DepartmentEntity,
  FeeTypeEntity,
  GeneralCriterionEntity,
  GeneralDeclarationEntity,
  GeneralFeeEntity,
  IntakeEntity,
  OfferingDeclarationEntity,
  OfferingFeeEntity,
  ProgrammeEntity,
  ProgrammeOfferingEntity,
  SupportingInformationEntity,
  ProcessingFeeChallanEntity,
  ProcessingFeeChallanItemEntity,
  DesignatedBankEntity,
  PaymentEvidenceEntity,
  OnlinePaymentTransactionEntity,
  BankReconciliationImportEntity,
  BankReconciliationRecordEntity,
  DocumentTypeEntity,
  OfferingRequiredDocumentEntity,
  ApplicantDocumentEntity,
  ApplicantDocumentFileEntity,
  DocumentVerificationAuditEntity,
  TestCentreEntity,
  TestSessionEntity,
  TestSessionProgrammeEntity,
  ApplicationAdmitCardEntity,
  ApplicationAttendanceEntity,
  ApplicationAttendanceScanEntity,
  ApplicationAttendanceAuditEntity,
  ApplicationEntryTestOutcomeEntity,
  AcademicLevelRequirementEntity,
  MeritFormulaTemplateEntity,
  MeritFormulaTemplateComponentEntity,
  OfferingMeritFormulaEntity,
  OfferingMeritFormulaComponentEntity,
  AdmissionOfferFeeChallanEntity,
  AdmissionOfferFeeChallanItemEntity,
  AdmissionOfferFeeEvidenceEntity,
  SelectionSeatReleaseRunEntity,
} from './entities/index.js';

const entities = [
  FeeTypeEntity,
  CriteriaTypeEntity,
  DeclarationTypeEntity,
  DepartmentEntity,
  ProgrammeEntity,
  GeneralCriterionEntity,
  IntakeEntity,
  ProgrammeOfferingEntity,
  GeneralFeeEntity,
  OfferingFeeEntity,
  GeneralDeclarationEntity,
  OfferingDeclarationEntity,
  AdmissionCriterionEntity,
  SupportingInformationEntity,
  ApplicationEntity,
  ApplicationAcademicInformationEntity,
  ApplicationAcademicDocumentEntity,
  ApplicationProgrammeSelectionEntity,
  ApplicationProgrammeOptionEntity,
  ApplicationAddressEntity,
  ApplicationContactEntity,
  ApplicationDeclarationEntity,
  ApplicationStatusAuditEntity,
  ProcessingFeeChallanEntity,
  ProcessingFeeChallanItemEntity,
  DesignatedBankEntity,
  PaymentEvidenceEntity,
  OnlinePaymentTransactionEntity,
  BankReconciliationImportEntity,
  BankReconciliationRecordEntity,
  DocumentTypeEntity,
  OfferingRequiredDocumentEntity,
  ApplicantDocumentEntity,
  ApplicantDocumentFileEntity,
  DocumentVerificationAuditEntity,
  TestCentreEntity,
  TestSessionEntity,
  TestSessionProgrammeEntity,
  ApplicationAdmitCardEntity,
  ApplicationAttendanceEntity,
  ApplicationAttendanceScanEntity,
  ApplicationAttendanceAuditEntity,
  ApplicationEntryTestOutcomeEntity,
  AcademicLevelRequirementEntity,
  MeritFormulaTemplateEntity,
  MeritFormulaTemplateComponentEntity,
  OfferingMeritFormulaEntity,
  OfferingMeritFormulaComponentEntity,
  AdmissionOfferFeeChallanEntity,
  AdmissionOfferFeeChallanItemEntity,
  AdmissionOfferFeeEvidenceEntity,
  SelectionSeatReleaseRunEntity,
];

@Module({
  imports: [
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: () => ({
        ...buildDatabaseOptions(),
        entities,
        synchronize: false,
        migrationsRun: false,
        logging: process.env.NODE_ENV === 'development',
      }),
    }),
    TypeOrmModule.forFeature(entities),
  ],
  exports: [TypeOrmModule],
})
export class DatabaseModule {}
