import 'reflect-metadata';
import 'dotenv/config';
import { DataSource } from 'typeorm';
import { buildDatabaseOptions } from './database.config.js';
import {
  AdmissionCriterionEntity,
  ApplicationAcademicDocumentEntity,
  ApplicationAcademicInformationEntity,
  ApplicationAddressEntity,
  ApplicationContactEntity,
  ApplicationDeclarationEntity,
  ApplicationEntity,
  ApplicationProgrammeOptionEntity,
  ApplicationProgrammeSelectionEntity,
  CriteriaTypeEntity,
  DeclarationTypeEntity,
  DepartmentEntity,
  FeeTypeEntity,
  GeneralCriterionEntity,
  GeneralDeclarationEntity,
  GeneralFeeEntity,
  IntakeEntity,
  OfferingDeclarationEntity,
  OfferingFeeEntity,
  ProgrammeEntity,
  ProgrammeOfferingEntity,
  SupportingInformationEntity,
  ProcessingFeeChallanEntity,
  ProcessingFeeChallanItemEntity,
  DesignatedBankEntity,
  PaymentEvidenceEntity,
  OnlinePaymentTransactionEntity,
  BankReconciliationImportEntity,
  BankReconciliationRecordEntity,
  DocumentTypeEntity,
  OfferingRequiredDocumentEntity,
  ApplicantDocumentEntity,
  ApplicantDocumentFileEntity,
  DocumentVerificationAuditEntity,
  ApplicationStatusAuditEntity,
  TestCentreEntity,
  TestSessionEntity,
  TestSessionProgrammeEntity,
  ApplicationAdmitCardEntity,
  ApplicationAttendanceEntity,
  ApplicationAttendanceScanEntity,
  ApplicationAttendanceAuditEntity,
  ApplicationEntryTestOutcomeEntity,
  AcademicLevelRequirementEntity,
  MeritFormulaTemplateEntity,
  MeritFormulaTemplateComponentEntity,
  OfferingMeritFormulaEntity,
  OfferingMeritFormulaComponentEntity,
  AdmissionOfferFeeChallanEntity,
  AdmissionOfferFeeChallanItemEntity,
  AdmissionOfferFeeEvidenceEntity,
  SelectionSeatReleaseRunEntity,
} from './entities/index.js';

export const AppDataSource = new DataSource({
  ...buildDatabaseOptions(),
  entities: [
    FeeTypeEntity,
    CriteriaTypeEntity,
    DeclarationTypeEntity,
    DepartmentEntity,
    ProgrammeEntity,
    GeneralCriterionEntity,
    IntakeEntity,
    ProgrammeOfferingEntity,
    GeneralFeeEntity,
    OfferingFeeEntity,
    GeneralDeclarationEntity,
    OfferingDeclarationEntity,
    AdmissionCriterionEntity,
    SupportingInformationEntity,
    ApplicationEntity,
    ApplicationAcademicInformationEntity,
    ApplicationAcademicDocumentEntity,
    ApplicationProgrammeSelectionEntity,
    ApplicationProgrammeOptionEntity,
    ApplicationAddressEntity,
    ApplicationContactEntity,
    ApplicationDeclarationEntity,
    ProcessingFeeChallanEntity,
    ProcessingFeeChallanItemEntity,
    DesignatedBankEntity,
    PaymentEvidenceEntity,
    OnlinePaymentTransactionEntity,
    BankReconciliationImportEntity,
    BankReconciliationRecordEntity,
    DocumentTypeEntity,
    OfferingRequiredDocumentEntity,
    ApplicantDocumentEntity,
    ApplicantDocumentFileEntity,
    DocumentVerificationAuditEntity,
    ApplicationStatusAuditEntity,
    TestCentreEntity,
    TestSessionEntity,
    TestSessionProgrammeEntity,
    ApplicationAdmitCardEntity,
    ApplicationAttendanceEntity,
    ApplicationAttendanceScanEntity,
    ApplicationAttendanceAuditEntity,
    ApplicationEntryTestOutcomeEntity,
    AcademicLevelRequirementEntity,
    MeritFormulaTemplateEntity,
    MeritFormulaTemplateComponentEntity,
    OfferingMeritFormulaEntity,
    OfferingMeritFormulaComponentEntity,
    AdmissionOfferFeeChallanEntity,
    AdmissionOfferFeeChallanItemEntity,
    AdmissionOfferFeeEvidenceEntity,
    SelectionSeatReleaseRunEntity,
  ],
  migrations: ['src/database/migrations/*{.ts,.js}'],
  synchronize: false,
  logging: process.env.NODE_ENV === 'development',
});
